#!/bin/bash
# CCEM APM Pre-Tool-Use Hook — auto-generated by ActionEngine
# Reports tool invocation to APM heartbeat

AGENT_ID="${CLAUDE_AGENT_ID:-session-unknown}"
TOOL_NAME="${CLAUDE_TOOL_NAME:-unknown}"

curl -s -X POST http://localhost:3031/api/heartbeat \
  -H "Content-Type: application/json" \
  -d "{
    \"agent_id\": \"$AGENT_ID\",
    \"status\": \"working\",
    \"message\": \"Tool: $TOOL_NAME\"
  }" >/dev/null 2>&1 &
