#!/bin/bash
# CCEM APM Session Init Hook — auto-generated by ActionEngine
# Reports session start to APM at localhost:3031

PROJECT_ROOT="${CLAUDE_PROJECT_ROOT:-$(pwd)}"
SESSION_ID="${CLAUDE_SESSION_ID:-$(uuidgen | tr '[:upper:]' '[:lower:]')}"
PROJECT_NAME=$(basename "$PROJECT_ROOT")

curl -s -X POST http://localhost:3031/api/register \
  -H "Content-Type: application/json" \
  -d "{
    \"agent_id\": \"session-$SESSION_ID\",
    \"project\": \"$PROJECT_NAME\",
    \"role\": \"session\",
    \"status\": \"active\",
    \"session_id\": \"$SESSION_ID\"
  }" >/dev/null 2>&1 &
